name: lib_network
description: Flutter project network module.
version: 0.0.5
homepage:
repository: https://github.com/yeshu-cn/network

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

# publish_to: https://pub.dartlang.org
